language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .[test]

script:
  - pytest -v sphinxcontrib

# Add separate test environments for the docs and flake8 linter.

jobs:
  include:
    - name: "Docs"
      script: python -m sphinx.cmd.build -E -W -v -T doc/source doc/build
    - name: "Lint"
      install: pip install flake8
      script: flake8 -v sphinxcontrib setup.py
    - name: "Check Package"
      install: pip install twine
      script:
        - python setup.py sdist
        - twine check dist/*.tar.gz
