language: python

python:
  - "3.6"

# Add separate test environments for the docs and flake8 linter.

jobs:
  include:
    - name: "Docs"
      install: ~        
      script:
        - python setup.py bdist
        - pip install --find-links dist/ sphinxcontrib.datatemplates
        - python -m sphinx.cmd.build -E -W -v -T doc/source doc/build
    - name: "Lint"
      install: pip install flake8
      script: flake8 -v sphinxcontrib setup.py

