language: python

python:
  - "3.6"

# Add separate test environments for the docs and flake8 linter.

jobs:
  include:
    - name: "Docs"
      install:
        - python setup.py bdist
        - pip install --no-index --find-links=dist/ sphinxcontrib.datatemplates
      script: python sphinx-build -E -W -v -T doc/source doc/build
    - name: "Lint"
      install: pip install flake8
      script: flake8 -v sphinxcontrib setup.py

