language: python

python:
  - "3.6"

# Add separate test environments for the docs and flake8 linter.

jobs:
  include:
    - name: "Docs"
      script: python setup.py build_docs -E -W
    - name: "Lint"
      install: pip install flake8
      script: flake8 sphinxcontrib setup.py

